### ISSUE TITLE
homescreen dropdown menu?

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/OpenArchive#2]
Remove the “photo” “video” or “audio” dropdown.

We discussed removing this in our initial plan since the type of media should be implicit when uploading.

**Comment by vitriolix** [comment]
That drop down is unfortunately needed as its how you chose what capture mode the camera is in when we launch it.  Lots of devices have cameras that don't let you switch from video to photo after the fact.  It also is how we decide if we are lanching the audio recorder as well which is a different app than the camera.  marking as wontfix
